### ISSUE TITLE
`pkg_resources` deprecation

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/enterprise#428]
While debugging some issues with a new environment, I noticed that `from enterprise.pulsar import Pulsar` raises a `DeprecationWarning`:
```
[...]/enterprise/signals/utils.py:13: UserWarning: pkg_resources is deprecated as an API.
See https://setuptools.pypa.io/en/latest/pkg_resources.html.
The pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import Requirement, resource_filename
```
Apparently `pkg_resources` (from `setuptools`), which is used in `signals/utils.py`, has been deprecated in favor of the native Python module [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html).

**Comment by vhaasteren** [comment]
That function is weird. It is a literal copy-paste of a function of libstempo, and it uses the libstempo data file which is why it needs pkg_resources. Whoever uses that function should just import it from libstempo. No piece of code in enterprise uses it as far as I can see. I think we should simply delete the function `make_ecc_interpolant` from enterprise and be done with it. I do not see it being used in enterprise_extensions either.

What do you think, @AaronDJohnson ?

**Comment by AaronDJohnson** [comment]
Given that we don't require libstempo as a dependency anymore, I think it's important that we remove it. The function itself is only a call to `scipy.interpolate.interp1d` which can be performed in a single line, if it is needed.

**Comment by vhaasteren** [comment]
Exactly

And even then, doing an `import libstempo.toasim.make_ecc_interpolant `would provide the functionality

**Comment by astrolamb** [comment]
Uh... @levischult found this bug and I fixed it before seeing this thread. See #429

This PR also removes a full package import in `enterprise.pulsar`, so that's at least useful...

**Comment by meyers-academic** [comment]
Just a heads up, I did a fresh install of enterprise today via `conda` (with `conda install enterprise_extensions`) and I'm still getting this error. Had to pin to `setuptools < 82.0` to get it to import.

**Comment by astrolamb** [comment]
@meyers-academic you need install from the `dev` branch using pip
```
pip install enterprise-pulsar@dev
```

At some point, we need to merge everything to `master`

**Comment by astrolamb** [comment]
Fixes merged from dev to master in #454 and released as [v3.5.0](https://github.com/nanograv/enterprise/releases/tag/v3.5.0)
